---

- hosts: web
  become: yes
  vars:
    certbot_install_from_source: yes
    certbot_repo: https://github.com/certbot/certbot.git
    certbot_version: master
    certbot_keep_updated: yes
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user }}"
    certbot_auto_renew_hour: 3
    certbot_auto_renew_minute: 30
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_admin_email: email@example.com
    certbot_create_if_missing: yes
    certbot_create_standalone_stop_services: []
    certbot_certs:
      - domains:
        - ansibletest.tylerturk.com

  roles:
    - certbotprereqs
    - geerlingguy.certbot
    - webserver

- hosts: db
  gather_facts: false
  become: Yes

  roles:
    - dbserver
